spring:
  flyway:
    baseline-on-migrate: true
  application:
    name: store
  datasource:
    url: jdbc:mysql://localhost:3306/store?createDatabaseIfNotExist=true
    username: root
    password: 123@Zuckerberg@12
    driver-class-name: com.mysql.cj.jdbc.Driver
stripe:
  apiUrl: https://api.stripe.com
  timeout: 1000
  enabled: true
  supported-currencies: USD, EUR, GBP
payment-gateway: paypal